import Head from 'next/head'
import Headersection from '../components/Headersection'


export default function Home() {
  return (
    <div className="bg-[#292929] min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Headersection/>
    </div>
  )
}






//bg-[#292929]